### ISSUE TITLE
IIS worker process profiling fails with "Unexpected error" message

### ISSUE THREAD

**Issue by markashleybell** [xoofx/ultra#11]
I'm not sure whether this is totally outside the scope of this project or not, and I'm not clear whether it's intended for working with .NET Framework code or just .NET Core... so if I'm just using it wrong, please feel free to close this!

My use case would be attaching to a running IIS worker process (`w3wp.exe`) to profile a web application. However, when I try that by attaching to the PID, I get the following error:

```
Unexpected error: The requested resource is in use. (0x800700AA)
```

![Screenshot 2024-11-26 153704](https://github.com/user-attachments/assets/3b38de6a-f29b-4038-8940-e201948eb04d)

Is this a bug, or am I doing something wrong (or is Ultra just not really intended for profiling web apps)?

**Comment by xoofx** [comment]
> Is this a bug, or am I doing something wrong (or is Ultra just not really intended for profiling web apps)?

I don't think it is a bug with ultra but something else with ETW/Windows that would happen if you were using another ETW based profiler. Others have been experiencing this similar issue:

- https://github.com/dotnet/BenchmarkDotNet/issues/2139
- https://github.com/microsoft/perfview/issues/1726
- https://github.com/microsoft/perfview/issues/1723

You could try the workaround described [here](https://github.com/microsoft/perfview/issues/1726#issuecomment-1276697339) and see if it solves your issue.

**Comment by markashleybell** [comment]
Yep, I can confirm that running the following in my elevated Powershell terminal allowed me to profile successfully:

```powershell
Set-MpPreference -DisableTDTFeature $true
```

And ultra works really well! Looking forward to having a proper play with this tomorrow.

Incidentally (for anyone who stumbles across this), you can also re-enable the disabled feature easily enough after a profiling session:

```powershell
# Re-enable TDT
Set-MpPreference -DisableTDTFeature $false

# Check the current status
Get-MpPreference | Select-Object -ExpandProperty IntelTDTEnabled
```
