### ISSUE TITLE
Detach profiler

### ISSUE THREAD

**Issue by KirillOsenkov** [xoofx/ultra#12]
When using `ultra profile --pid=1234` it would be nice when my scenario is done, to press a button to stop profiling and detach to keep the profilee process running.

Otherwise I have to kill the process to stop profiling.

**Comment by xoofx** [comment]
> it would be nice when my scenario is done, to press a button to stop profiling and detach to keep the profilee process running.

It should be `CTRL+C` pressed just once, it should be in the doc, but I should probably add a reminder when launching the profiler.

> Also when starting an .exe process, would be nice to start with profiling paused, so I can reach my scenario, the press a button to start recording, then press the button again to stop and detach.

Yep, it's something that can be added easily. Will do that.

**Comment by xoofx** [comment]
Fixed via 96a2a20 

Should be available soon in `1.4.0+`

**Comment by KirillOsenkov** [comment]
As I already said, WOW

**Comment by EgorBo** [comment]
It'd also be nice to have `--delay` and `--duration` arguments for automated scenarios 🙂

**Comment by xoofx** [comment]
> It'd also be nice to have --delay and --duration arguments for automated scenarios 🙂

Oh, yep, I wanted to add that and forgot again, agreed 🙂

**Comment by xoofx** [comment]
> It'd also be nice to have --delay and --duration arguments for automated scenarios 🙂

Added via 2868266

Should be available in `1.5.0+`
