### ISSUE TITLE
Symbols aren't loaded for --pid mode

### ISSUE THREAD

**Issue by EgorBo** [xoofx/ultra#13]
I've integrated ultra into my bot here https://github.com/EgorBot/runtime-utils/issues/173 🙂 but it seems like it's not picking up symbols when it's attached to an already running app via `--pid` (it works when it itself starts the app).

Repro:
```cs
using System.Text.Json;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Perf_Basic).Assembly).Run(args);

public class Perf_Basic
{
    static readonly Employee[] Data = Enumerable.Range(1, 4096)
        .Select(i => new Employee("John", "Manager", 30, 185.5, new DateTime(1990, 10, 10),
            new Employee("John", "Developer", 30 + i, 185.5, new DateTime(1990, 10, 10), null))).ToArray();

    [Benchmark]
    public Employee[]? JsonRoundtrip()
    {
        var str = JsonSerializer.Serialize(Data);
        return JsonSerializer.Deserialize<Employee[]>(str);
    }
}

public record Employee(string name, string title, int age, double height, DateTime applyDate, Employee? manager);
```
which I then build & run as
```
dotnet publish -c Release --sc -r win-x64 -f net9.0 && .\bin\Release\net9.0\win-x64\publish\ConsoleApp10.exe --filter * --noForcedGCs --noOverheadEvaluation --disableLogFile --maxWarmupCount 8 --minIterationCount 15000000 --maxIterationCount 20000000 -a perfarts -i
```
and in a separate window:
```
ultra profile --pid $(Get-Process -Name ConsoleApp10).Id
```
I tried to use `dotnet-symbol --symbols` and `<DebugType>` with no luck

**Comment by EgorBo** [comment]
> hm... but isn't BenchmarkDotNet launching another process actually to run the actual benchmarks?

not with `-i` parameter (stands for InProcessToolchain)

**Comment by xoofx** [comment]
> not with -i parameter (stands for InProcessToolchain)

Hm, interesting. Have you ever tried with `perfview` similarly?

I will double check locally what is happening, but I'm not doing anything particular for the symbol resolution, so BenchmarkDotNet might still interfere in some ways...

**Comment by xoofx** [comment]
So I just tried your exact steps above and I got it working, so it might be something else...

<img width="749" alt="image" src="https://github.com/user-attachments/assets/a6d9af93-41ad-4c01-ae6a-59e57e7bcc82">

**Comment by xoofx** [comment]
Nice! Really cool to have the profile linkable via a URL
