### ISSUE TITLE
Provide the resulting filename as an argument

### ISSUE THREAD

**Issue by sebastienros** [xoofx/ultra#8]
For automation purposes it would be simpler to be able to provide the destination filename. Right now I need to extract it from `Generated Firefox Profiler JSON file -> [green]{fileOutput}[/] -`. This could include the destination folder.

**Comment by xoofx** [comment]
Agreed 🙂 fixed by 67cba04. Usage: `ultra profile --output my_base_file_name ...`

`my_base_file_name` is the name without `json.gz`. It will always append `json.gz`. The merged ETL files are also using this base file name.

Should be soon available via `1.3.0+`
